### PR TITLE
[DATA] [FRNT] Compute and display rank within f2p.wiki

### PR DESCRIPTION
**Pull request by jackastner**
This pull request adds a players rank within f2p.wiki to their personal hiscores page. 

I ended up implementing this just by computing a players ranks each time their page is requested. This isn't ideal since it means adding a non-negligible database query on each request. On the other hand, it's nice because no extra work is done for players who never view their personal hiscores (do you have data on how many players actually check their page? I suspect it's not a huge fraction of the entire database). 

The other way to do this would be computing and storing a players rank on every update.  The reason to do this is to avoid extra work when a hiscores page is requested. Of course, this adds some extra work on each update. The real issue with this approach is that incrementing a players rank requires decrementing the rank of some number of players between the old and new rank. To avoid race conditions during the update, all of these rows would need to be locked. I don't think sqlite supports row level locking so, the whole table would need to be locked, effectively stopping any concurrent updates.

Anyways, this is just a quick implementation I threw together that only handles rank for skills and clues. I can add rank for gains/records but I wanted to see if you were cool with how I'm calculating rank before I spend too much time on it.

### CODE REVIEW

**Comment by vmeow** [comment]
I've gone ahead and pushed this to "staging", f2pehp2.herokuapp.com, which has ~5k players. Feel free to check it out.

There may be some small quirks such as with 0 EHP skills as HP, but this generally looks really good.

Will let it sit for a while, but I'm impressed with the speed, which was my biggest concern.

I guess this is my approval unless something major comes up.

**Comment by vmeow** [comment]
Oh and if you'd like, I can post this in some of the F2P discords or something, and ask some people to do some testing on the staging site.

**Comment by jackastner** [comment]
I finally got around to putting some more work into this. It now does ranks for gains and record gain.  I've done my best to work out bugs in the rank ordering but, chances are they're some edge cases I didn't hit. It seems to work for the most part though.

If you push this to staging and nothing is obviously broken, I think it should be good to go.

**Comment by vmeow** [comment]
super super sorry for taking so long to review this - I've been super burned out lately. I'll be testing this branch out this week and probably deploying it

**Comment by puremana** [comment]
> super super sorry for taking so long to review this - I've been super burned out lately. I'll be testing this branch out this week and probably deploying it

We should have a staging branch that pushes to your heroku staging server so I can chuck things on there to test too :)

**Comment by vmeow** [comment]
@puremana just added you as collaborator to f2pehp2; do feel free to push to it whenever. url is f2pehp2.herokuapp.com

**Comment by vmeow** [comment]
Thanks again for the contribution!

**Pull request merged**
